@startuml blogging-context
title "Context Diagram: Admninistrator"
!include <C4/C4_Component>

' Persons
Person(user, "Owner users", "Users the application")

' Applications
System(adminSystem, "Web Administrator", "Administrador de la solución")
System(mailSystem, "Mail sender", "Sends emails to users (Net Core)")
System(logSystem, "Log register", "Registers logs into database BigQuery")
System(summarySystem, "Summary data", "Recovery from BigQuery database")
System(loggerSystem, "Logger register", "Register logger into database BigQuery")
System(notificationSystem, "Notification sender", "Sends notification to users")

' Relationships
Rel_R(user, adminSystem, "Uses", "HTTPS")
Rel_D(adminSystem, mailSystem, "Uses", "AMQP")
Rel_D(adminSystem, notificationSystem, "Uses", "AMQP")
Rel_D(adminSystem, summarySystem, "Uses", "AMQP")
Rel_D(adminSystem, logSystem, "Uses", "AMQP")
Rel_D(adminSystem, loggerSystem, "Uses", "AMQP")

footer Drawn with PlantUML v. %version() and C4-PlantUML v. C4Version()
@enduml